"""Apple Silicon boot finalization isolated from configured-target inputs.

This module is imported only by the finalized-boot phase. Keeping the GRUB
selector and boot artwork boundary here lets a boot-only repair reuse the
verified package repository, base images, and configured target checkpoints.
"""

from __future__ import annotations

from pathlib import Path

from .context import InstallContext


ASAHI_MKINITCPIO_HOOKS_DROPIN = r'''# Generated by the Omarchy Apple Silicon image builder.
_omarchy_asahi_hooks=()
_omarchy_asahi_added=false
for _omarchy_asahi_hook in "${HOOKS[@]}"; do
  if [[ $_omarchy_asahi_hook == asahi ]]; then
    _omarchy_asahi_added=true
  fi
  if [[ $_omarchy_asahi_hook == filesystems && $_omarchy_asahi_added == false ]]; then
    _omarchy_asahi_hooks+=(asahi)
    _omarchy_asahi_added=true
  fi
  _omarchy_asahi_hooks+=("$_omarchy_asahi_hook")
done
if [[ $_omarchy_asahi_added == false ]]; then
  _omarchy_asahi_hooks+=(asahi)
fi
HOOKS=("${_omarchy_asahi_hooks[@]}")
unset _omarchy_asahi_hooks _omarchy_asahi_hook _omarchy_asahi_added
'''


def _set_shell_assignment(text: str, name: str, value: str) -> str:
    from . import configured_phases as shared

    replacement = f'{name}="{value}"'
    pattern = rf"^#?{shared.re.escape(name)}=.*$"
    if shared.re.search(pattern, text, flags=shared.re.MULTILINE):
        return shared.re.sub(
            pattern,
            replacement,
            text,
            count=1,
            flags=shared.re.MULTILINE,
        )
    return text.rstrip() + "\n" + replacement + "\n"


def _asahi_kernel_source(ctx: InstallContext, kernel: str) -> Path:
    matches = []
    for pkgbase in sorted((ctx.target / "usr/lib/modules").glob("*/pkgbase")):
        if pkgbase.read_text().strip() != kernel:
            continue
        source = pkgbase.parent / "vmlinuz"
        if source.is_file() and source.stat().st_size:
            matches.append(source)
    if len(matches) != 1:
        raise RuntimeError(
            f"expected one populated {kernel} kernel under /usr/lib/modules, "
            f"found {len(matches)}"
        )
    return matches[0]


def _prepare_asahi_kernel_and_initramfs(
    ctx: InstallContext,
) -> tuple[Path, Path]:
    from . import configured_phases as shared

    storage = shared._storage_intent(ctx)
    kernel = storage.get("kernel") or (
        ctx.user_configuration.get("kernels") or ["linux-asahi"]
    )[0]
    if kernel != "linux-asahi":
        raise RuntimeError(f"Asahi GRUB requires linux-asahi, got {kernel}")

    boot_mount = storage.get("boot_mount", "/boot")
    if boot_mount != "/boot":
        raise RuntimeError(f"Asahi GRUB requires boot_mount=/boot, got {boot_mount}")

    boot_dir = ctx.target / "boot"
    boot_dir.mkdir(parents=True, exist_ok=True)
    kernel_target = boot_dir / f"vmlinuz-{kernel}"
    shared.shutil.copy2(_asahi_kernel_source(ctx, kernel), kernel_target)

    preset = ctx.target / "etc/mkinitcpio.d" / f"{kernel}.preset"
    preset.parent.mkdir(parents=True, exist_ok=True)
    preset.write_text(
        f'ALL_kver="/boot/vmlinuz-{kernel}"\n'
        "PRESETS=('default')\n"
        f'default_image="/boot/initramfs-{kernel}.img"\n'
    )

    hooks = ctx.target / "etc/mkinitcpio.conf.d/90-omarchy-asahi.conf"
    hooks.parent.mkdir(parents=True, exist_ok=True)
    hooks.write_text(ASAHI_MKINITCPIO_HOOKS_DROPIN)

    shared.subprocess.run(
        ["arch-chroot", str(ctx.target), "mkinitcpio", "-P"],
        check=True,
    )
    initramfs = boot_dir / f"initramfs-{kernel}.img"
    if not initramfs.is_file() or not initramfs.stat().st_size:
        raise RuntimeError(f"{initramfs} missing or empty after mkinitcpio")
    return kernel_target, initramfs


def _configure_asahi_grub_defaults(ctx: InstallContext) -> Path:
    grub_default = ctx.target / "etc/default/grub"
    grub_default.parent.mkdir(parents=True, exist_ok=True)
    text = grub_default.read_text() if grub_default.exists() else ""
    for name, value in (
        ("GRUB_DISTRIBUTOR", "Omarchy"),
        ("GRUB_TIMEOUT", "3"),
        ("GRUB_TIMEOUT_STYLE", "menu"),
        ("GRUB_CMDLINE_LINUX", "zswap.enabled=0 rootfstype=btrfs"),
        ("GRUB_CMDLINE_LINUX_DEFAULT", "loglevel=3 quiet splash"),
    ):
        text = _set_shell_assignment(text, name, value)
    grub_default.write_text(text)
    return grub_default


ASAHI_UPDATE_GRUB_SCRIPT = r"""
set -euo pipefail

root_device=${1:?missing root device}
root_uuid=${2:?missing root UUID}
device_directory=/dev/disk/by-uuid
link=$device_directory/$root_uuid
created=false

fail() {
  printf 'omarchy-asahi-update-grub: %s\n' "$1" >&2
  exit 1
}

[[ $root_device =~ ^/dev/loop[0-9]+$ ]] || fail "unsafe root device"
[[ $root_uuid =~ ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$ ]] \
  || fail "invalid root filesystem UUID"
[[ -b $root_device ]] || fail "root device is unavailable"
resolved_root=$(readlink -f -- "$root_device")
[[ -n $resolved_root ]] || fail "root device cannot be resolved"

for directory in /dev/disk "$device_directory"; do
  [[ ! -L $directory ]] || fail "unsafe root UUID device directory"
  [[ ! -e $directory || -d $directory ]] || fail "unsafe root UUID device directory"
  mkdir -p -- "$directory"
done

if [[ -L $link ]]; then
  resolved_link=$(readlink -f -- "$link") \
    || fail "root UUID device link mismatch"
  [[ $resolved_link == "$resolved_root" ]] \
    || fail "root UUID device link mismatch"
elif [[ -e $link ]]; then
  fail "root UUID device path is not a symlink"
else
  ln -s -- "$root_device" "$link"
  created=true
fi

cleanup() {
  status=$?
  trap - EXIT
  if [[ $created == true ]]; then
    [[ -L $link ]] || fail "root UUID device link changed during GRUB generation"
    resolved_link=$(readlink -f -- "$link") \
      || fail "root UUID device link changed during GRUB generation"
    [[ $resolved_link == "$resolved_root" ]] \
      || fail "root UUID device link changed during GRUB generation"
    rm -- "$link"
  fi
  exit "$status"
}
trap cleanup EXIT

BOOT_PART=/boot \
EFI_PART=/boot/efi \
TARGET=/boot/efi/EFI/BOOT/BOOTAA64.EFI \
  /usr/bin/update-grub
""".lstrip()


def _run_asahi_update_grub(
    ctx: InstallContext,
    root_device: str,
    root_uuid: str,
) -> None:
    """Run update-grub with its UUID mapping inside arch-chroot's /dev."""
    from . import configured_phases as shared

    if shared.re.fullmatch(
        r"[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-"
        r"[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}",
        root_uuid,
    ) is None:
        raise RuntimeError("invalid root filesystem UUID")
    if shared.re.fullmatch(r"/dev/loop[0-9]+", root_device) is None:
        raise RuntimeError(f"unsafe Asahi package root device: {root_device}")

    shared.subprocess.run(
        [
            "arch-chroot",
            str(ctx.target),
            "/bin/bash",
            "-s",
            "--",
            root_device,
            root_uuid,
        ],
        input=ASAHI_UPDATE_GRUB_SCRIPT,
        text=True,
        check=True,
    )


def finalize_asahi_grub_boot(ctx: InstallContext) -> None:
    """Build the standard Asahi U-Boot to removable GRUB to Linux chain."""
    from . import configured_phases as shared

    if ctx.encrypt or shared._provision_install_encrypted(ctx):
        raise RuntimeError(
            "Asahi full-OS packages do not yet support encrypted root images"
        )

    boot = shared._boot_intent(ctx)
    if boot.get("register_firmware"):
        raise RuntimeError(
            "Asahi full-OS package finalization must not mutate UEFI NVRAM"
        )
    if boot["esp_mount"] != "/boot/efi":
        raise RuntimeError(
            f"Asahi GRUB requires esp_mount=/boot/efi, got {boot['esp_mount']}"
        )

    required = (
        ctx.target / "usr/bin/update-grub",
        ctx.target / "usr/bin/grub-mkconfig",
        ctx.target / "usr/lib/grub/arm64-efi",
        ctx.target / "boot/efi/m1n1/boot.bin",
    )
    for path in required:
        if not path.exists() or (path.is_file() and not path.stat().st_size):
            raise RuntimeError(f"required Asahi boot input missing or empty: {path}")

    shared.info("› building linux-asahi initramfs")
    _prepare_asahi_kernel_and_initramfs(ctx)
    _configure_asahi_grub_defaults(ctx)
    root_device = shared._btrfs_root_device(ctx)
    root_uuid = shared._blkid_uuid(root_device)

    for directory in (
        ctx.target / "boot/grub",
        ctx.target / "boot/efi/EFI/BOOT",
    ):
        if directory.is_symlink() or (
            directory.exists() and not directory.is_dir()
        ):
            raise RuntimeError(f"unsafe Asahi GRUB output directory: {directory}")
        directory.mkdir(parents=True, exist_ok=True)

    shared.info("› generating Asahi removable GRUB image (no NVRAM mutation)")
    _run_asahi_update_grub(ctx, root_device, root_uuid)

    shared.subprocess.run(
        ["arch-chroot", str(ctx.target), "btrfs", "quota", "disable", "/"],
        check=False,
        capture_output=True,
    )
    for output in (
        ctx.target / "boot/grub/grub.cfg",
        ctx.target / "boot/efi/EFI/BOOT/BOOTAA64.EFI",
    ):
        if not output.is_file() or not output.stat().st_size:
            raise RuntimeError(f"Asahi GRUB output missing or empty: {output}")
